### PR TITLE
Improved Items

### PR DESCRIPTION
**Pull request by Edgarware**
Now that we actually understand these things better:
* add Item.load_all
* Add Tables for stat types and adjustment types
* fix Item.adjustments to include all the prefixes & suffixes
* add is_broken

Also threw in some of how these affect players:
* included items in player ratings
* added lazy-loading for item_attr
* rounding stars to nearest tenth rather than nearest half-star

I'm not sure if I like always including items in the rating, in the off chance the user wants to get the unaltered version. We also probably need to figure out how we're including the player attribute modifications but I'd rather not have to write a lazy-load function for all 30-some fields.

### CODE REVIEW

**Comment by jmaliksi** [comment]
hmm, I think we'd want to match the blaseball backend API if possible. I'm guessing it's the frontend that's adding the calculated rating to the item ratings?

**Comment by Edgarware** [comment]
Correct, the frontend is what's adding the item ratings. But we already duplicate some frontend stuff, like soulscreams and bet payouts. Maybe just make a separate get_rating function that can include items as an option?

**Comment by jmaliksi** [comment]
yeah a separate explicit rating function makes sense. Maybe we then convert the rating properties to just read from the API if available?

**Comment by Edgarware** [comment]
OK done pushed an update. So now Player has `get_X_rating` and `get_X_stars` to handle the item/rounding issues. `Player.X_rating` is staying around to match the backend (or the calculated on in cases where it does not exist) and `Player.X_stars` is now unchanged but has a new Depreciation warning to guide people to the new functions. I'll probably throw them out completely in 6.0

**Review by jmaliksi — APPROVED** [review]

**Pull request merged**
